package com.ironhack.TaskManager.models;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity // Marks this class as a JPA entity, mapping it to a database table
@Data // Generates getters, setters, equals, hashCode, and toString methods
@NoArgsConstructor // Generates a no-argument constructor
@AllArgsConstructor // Generates a constructor with all fields as arguments
public class UserTask {

    @Id // Marks this field as the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the ID will be auto-generated by the database
    private Long id;

    @ManyToOne(optional = false) // Defines a many-to-one relationship with the User entity
    @JoinColumn // Specifies the foreign key column for the relationship
    private User user;

    @OneToOne(optional = false) // Defines a one-to-one relationship with the Task entity
    @JoinColumn(unique = true) // Specifies the foreign key column and enforces uniqueness
    private Task task;

    private String taskType; // Stores additional comments related to the UserTask
}